#ifndef __LIBRARIES_H
#define __LIBRARIES_H
#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_BusIO_Register.h>
#include <Adafruit_Sensor.h>
#include "FS.h"
#include "webserver.h"
#include <network_config.h>
#endif //__LIBRARIES_H